<!-- ===== REDDIT-STYLE FEED + STICKY RIGHT SIDEBAR ===== -->
    <section id="feed" class="feed-section">
        <div class="container">
            <div class="row g-4">
                <!-- Left: Feed Posts -->
                <div class="col-lg-8">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <h4 class="fw-bold mb-0">Community Feed</h4>
                        <span class="text-muted small">Showing 50 recent issues</span>
                    </div>
                    
                    <!-- Sort Bar -->
                    <div class="sort-bar">
                        <button class="sort-btn active" onclick="filterPosts('hot')">🔥 Hot</button>
                        <button class="sort-btn" onclick="filterPosts('new')">🆕 New</button>
                        <button class="sort-btn" onclick="filterPosts('top')">📈 Top</button>
                        <button class="sort-btn" onclick="filterPosts('rising')">⬆ Rising</button>
                    </div>
                    
                    <!-- Posts Container -->
                    <div id="feedPosts">
                        <!-- Posts will be generated by JavaScript -->
                    </div>
                </div>
                
                <!-- Right: Sticky Sidebar with Dashboard & Heatmap -->
                <div class="col-lg-4">
                    <div class="sticky-sidebar">
                        <!-- Issue Dashboard Card -->
                        <div class="dashboard-card slide-in-right" id="dashboardCard">
                            <div class="card-header d-flex align-items-center gap-2">
                                <span class="d-inline-block rounded-circle bg-danger" style="width:10px;height:10px;"></span>
                                <span class="d-inline-block rounded-circle bg-warning" style="width:10px;height:10px;"></span>
                                <span class="d-inline-block rounded-circle bg-success" style="width:10px;height:10px;"></span>
                                <span class="ms-2">Issue Dashboard</span>
                            </div>
                            <div class="card-body">
                                <div class="row g-2 mb-3">
                                    <div class="col-4 dashboard-stat">
                                        <div class="number text-primary">24</div>
                                        <div class="label">Open Issues</div>
                                    </div>
                                    <div class="col-4 dashboard-stat">
                                        <div class="number text-warning">12</div>
                                        <div class="label">In Progress</div>
                                    </div>
                                    <div class="col-4 dashboard-stat">
                                        <div class="number text-success">8</div>
                                        <div class="label">Resolved</div>
                                    </div>
                                </div>
                                <div class="preview-map position-relative rounded-3 overflow-hidden"
                                  style="height:250px;">

                                  <img
                                      src="map.png"
                                      alt="Chennai Heatmap"
                                      style="
                                          width:100%;
                                          height:100%;
                                          object-fit:cover;
                                          border-radius:10px;
                                      ">

                                  <div class="position-absolute text-white px-2 py-1 rounded"
                                      style="
                                          bottom:10px;
                                          left:10px;
                                          background:rgba(0,0,0,.5);
                                          font-size:12px;
                                      ">
                                      Live Heatmap
                                  </div>

                              </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </section>